/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package prolab2proje4;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ous
 */
public class Kayıt_Sorgulama extends javax.swing.JFrame {

    ArrayList arac_idlist = new ArrayList();
    ArrayList ilan_isimlist = new ArrayList();
    ArrayList markalist = new ArrayList();
    ArrayList modellist = new ArrayList();
    ArrayList kilometre = new ArrayList();
    ArrayList yakitt = new ArrayList();
    ArrayList vitess = new ArrayList();
    ArrayList fiyatlist = new ArrayList();
    ArrayList renklist = new ArrayList();
    ArrayList sehirlist = new ArrayList();
    ArrayList il_tarih = new ArrayList();
    
    
    
    
    static final String JDBC_DRIVER = "com.mysql.jdbc.Driver";
        static final String DOMAIN_NAME = "localhost";
        static final String DB_NAME = "otomobil_yonetim";
        static final String DB_URL = "jdbc:mysql://localhost:3306/otomobil_yonetim";
        
        static final String USER = "root";
        static final String PASS = "";
    /**
     * Creates new form Kayıt_Sorgulama
     */
    public Kayıt_Sorgulama() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        vites = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        km_min = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        model = new javax.swing.JTextField();
        fiyat_min = new javax.swing.JTextField();
        renk = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        sehir = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        yakit = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        marka = new javax.swing.JTextField();
        goster = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fiyat_max = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        km_max = new javax.swing.JTextField();
        tarih = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablo = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        ilanad1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        vites.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Manuel", "Otomatik" }));

        jLabel10.setText("Km Min:");

        jLabel9.setText("Renk:");

        jLabel6.setText("Model:");

        jLabel2.setText("Fiyat Min:");

        renk.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Mavi", "Sarı", "Kırmızı", "Siyah", "Beyaz", "Yeşil" }));

        jLabel3.setText("İlan Tarihi:");

        jLabel7.setText("Yakıt:");

        jLabel4.setText("Şehir:");

        sehir.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "ISTANBUL", "BURSA", "KOCAELI", "IZMIR", "ANKARA", "ANTALYA" }));

        jLabel5.setText("Marka:");

        yakit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "Benzin", "Dizel", "LPG" }));

        jLabel8.setText("Vites:");

        goster.setText("Göster");
        goster.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gosterMouseClicked(evt);
            }
        });

        jLabel1.setText("Fiyat Max:");

        jLabel11.setText("Km Max:");

        tarih.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "", "1 Gün", "1 Hafta", "1 Ay", "1 Yıl" }));

        tablo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tablo);

        jLabel12.setText("İlan Adı");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(88, 88, 88)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fiyat_min)
                            .addComponent(model, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                            .addComponent(ilanad1)
                            .addComponent(vites, javax.swing.GroupLayout.Alignment.TRAILING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(km_min, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel11)
                                .addGap(9, 9, 9))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(sehir, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(marka, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(yakit, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(28, 28, 28)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel12))))
                        .addComponent(km_max)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(goster)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(29, 29, 29)
                                .addComponent(renk, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(fiyat_max, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(380, Short.MAX_VALUE))))
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tarih, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ilanad1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(sehir, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiyat_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fiyat_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(model, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(marka, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(renk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vites, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(km_min, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(km_max, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(goster))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void gosterMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gosterMouseClicked
                Connection cnn = null;
                Statement stm = null;
                PreparedStatement psmt = null;
                int i = 0;
                
                try {
                Class.forName("com.mysql.jdbc.Driver");
                cnn = DriverManager.getConnection(DB_URL, USER, PASS);
                
                String sql = "SELECT * FROM tbl_ilan,tbl_araba WHERE";
                
                if(sehir.getSelectedIndex()!=0){
                    sql+=" Ilan_SehirID="+sehir.getSelectedIndex()+" AND";
                }
                if(yakit.getSelectedIndex()!=0){
                    sql+=" Araba_YakitTuruID="+yakit.getSelectedIndex()+" AND";
                }
                if(vites.getSelectedIndex()!=0){
                    sql+=" Araba_VitesTuruID="+vites.getSelectedIndex()+" AND";
                }
                if(renk.getSelectedIndex()!=0){
                    sql+=" Araba_RenkID="+renk.getSelectedIndex()+" AND";
                }
                if(!fiyat_min.getText().equals("") && !fiyat_max.getText().equals("")){
                    sql+=" Ilan_Fiyat BETWEEN "+Integer.parseInt(fiyat_min.getText())+" AND "+Integer.parseInt(fiyat_max.getText())+" AND";
                }
                if(!km_min.getText().equals("") && !km_max.getText().equals("")){
                    sql+=" Ilan_Km BETWEEN "+Integer.parseInt(km_min.getText())+" AND "+Integer.parseInt(km_max.getText())+" AND";
                }
                if(tarih.getSelectedIndex()!=0){
                    if(tarih.getSelectedIndex()==1){
                    sql+=" Ilan_Tarih BETWEEN CAST('2018-05-22' AS DATE) AND CAST('2018-05-23' AS DATE) AND";
                    }
                    if(tarih.getSelectedIndex()==2){
                    sql+=" Ilan_Tarih BETWEEN CAST('2018-05-16' AS DATE) AND CAST('2018-05-23' AS DATE) AND";
                    }
                    if(tarih.getSelectedIndex()==3){
                    sql+=" Ilan_Tarih BETWEEN CAST('2018-04-23' AS DATE) AND CAST('2018-05-23' AS DATE) AND";
                    }
                    if(tarih.getSelectedIndex()==4){
                    sql+=" Ilan_Tarih BETWEEN CAST('2017-05-13' AS DATE) AND CAST('2018-05-23' AS DATE) AND";
                    }
                    }
                if(!marka.getText().equals("")){
                    sql+=" Araba_Marka='"+marka.getText()+"' AND";
                }
                if(!model.getText().equals("")){
                    sql+=" Araba_Model='"+model.getText()+"' AND";
                }
                if(!ilanad1.getText().equals("")){
                     sql+=" Ilan_Adi LIKE '%"+ilanad1.getText()+"%' AND";
                }
                
                
                sql+=" tbl_ilan.Ilan_ArabaID=tbl_araba.ArabaID";
                stm = cnn.createStatement();
                ResultSet rs = stm.executeQuery(sql);
                
               
                
                while (rs.next()){
                    arac_idlist.add(rs.getString("ArabaID"));
                    ilan_isimlist.add(rs.getString("Ilan_Adi"));
                    markalist.add(rs.getString("Araba_Marka"));
                    modellist.add(rs.getString("Araba_Model"));
                    kilometre.add(rs.getString("Ilan_Km"));
                    vitess.add(rs.getString("Araba_VitesTuruID"));
                    yakitt.add(rs.getString("Araba_YakitTuruID"));
                    fiyatlist.add(rs.getString("Ilan_Fiyat"));
                    renklist.add(rs.getString("Araba_RenkID"));
                    sehirlist.add(rs.getString("Ilan_SehirID"));
                    il_tarih.add(rs.getString("Ilan_Tarih"));
                }
                
                organizetablo();
                
                
                
                
                
                
                } catch (ClassNotFoundException ex) {
                Logger.getLogger(Prolab2Proje4.class.getName()).log(Level.SEVERE, null, ex);
            } catch (SQLException ex) {
                Logger.getLogger(Prolab2Proje4.class.getName()).log(Level.SEVERE, null, ex);
            }
    }//GEN-LAST:event_gosterMouseClicked

    private void organizetablo(){
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Arac ID");
        model.addColumn("İlan İsmi");
        model.addColumn("Marka");
        model.addColumn("Model");
        model.addColumn("Kilometre");
        model.addColumn("Vites");
        model.addColumn("Yakıt");
        model.addColumn("Fiyat");
        model.addColumn("Renk");
        model.addColumn("Şehir");
        model.addColumn("İlan Tarih");
        
        
        for (int i = 0; i < arac_idlist.size(); i++) {
            model.addRow(new String[]{""+arac_idlist.get(i),""+ilan_isimlist.get(i),""+markalist.get(i),""
                    + ""+modellist.get(i),""+kilometre.get(i),vites(Integer.parseInt(""+vitess.get(i))),""
                   + yakit(Integer.parseInt(""+yakitt.get(i))),""+fiyatlist.get(i),renk(Integer.parseInt(""+renklist.get(i))),sehirs(Integer.parseInt(""+sehirlist.get(i))),""+il_tarih.get(i)});
            /*model.addRow(new String[]{""+ilan_isimlist.get(i)});
            model.addRow(new String[]{""+markalist.get(i)});
            model.addRow(new String[]{""+modellist.get(i)});
            model.addRow(new String[]{""+kilometre.get(i)});
            model.addRow(new String[]{""+vitess.get(i)});
            model.addRow(new String[]{""+yakitt.get(i)});
            model.addRow(new String[]{""+fiyatlist.get(i)});
            model.addRow(new String[]{""+renklist.get(i)});
            model.addRow(new String[]{""+sehirlist.get(i)});
            model.addRow(new String[]{""+il_tarih.get(i)});*/
            
        }
        
        tablo.setModel(model);
    }
    public String sehirs(int a){
        String b = "";
        if(a==1) b="ISTANBUL";
        if(a==2) b="BURSA";
        if(a==3) b="KOCAELI";
        if(a==4) b="IZMIR";
        if(a==5) b="ANKARA";
        if(a==6) b="ANTALYA";
        return b;
    }
    public String renk(int r){
        String c = "";
        if(r==1) c="MAVI";
        if(r==2) c="SARI";
        if(r==3) c="KIRMIZI";
        if(r==4) c="SIYAH";
        if(r==5) c="BEYAZ";
        if(r==6) c="YESIL";
        return c;
    }
    public String yakit(int y){
        String f = "";
        if(y==1) f="BENZIN";
        if(y==2) f="DIZEL";
        if(y==3) f="LPG";
        return f;
    }
    public String vites(int g){
        String v = "";
        if(g==1) v="MANUEL";
        if(g==2) v="OTOMATIK";
        return v;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgulama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayıt_Sorgulama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fiyat_max;
    private javax.swing.JTextField fiyat_min;
    private javax.swing.JButton goster;
    private javax.swing.JTextField ilanad1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField km_max;
    private javax.swing.JTextField km_min;
    private javax.swing.JTextField marka;
    private javax.swing.JTextField model;
    private javax.swing.JComboBox<String> renk;
    private javax.swing.JComboBox<String> sehir;
    private javax.swing.JTable tablo;
    private javax.swing.JComboBox<String> tarih;
    private javax.swing.JComboBox<String> vites;
    private javax.swing.JComboBox<String> yakit;
    // End of variables declaration//GEN-END:variables
}
